- name: List keys
  become: False
  command: ls -1 /home/core/.ssh/authorized_keys.d/
  register: keys
  always_run: yes
  when: "{{ exclusive }}"
  changed_when: False

- name: Delete keys for non-existing users
  file: path=/home/core/.ssh/authorized_keys.d/{{ item }} state=absent
  when: exclusive and item not in user_groups[group]
  with_items: "{{ keys.stdout_lines | default([]) }}"
  notify:
    - update authorized_keys

- name: Synchronize keys for users
  become: False
  authorized_key:
    user: core
    key: "{{ users[item].get('key') or lookup('file', 'files/keys/' + item + '.pub') }}"
    path: "{{ '/home/core/.ssh/authorized_keys.d/' + item }}"
    manage_dir: no
    exclusive: "{{ exclusive }}"
  with_items: "{{ user_groups[group] }}"
  notify:
    - update authorized_keys
