- become: False
  when: "{{ exclusive }}"
  block:
    - name: List keys
      command: ls -1 /home/core/.ssh/authorized_keys.d/
      register: keys
      check_mode: no
      changed_when: False

    - name: Delete keys for non-existing users
      file: path=/home/core/.ssh/authorized_keys.d/{{ item }} state=absent
      when: item not in user_groups[group]
      with_items: "{{ keys.stdout_lines }}"
      notify:
        - update authorized_keys

- name: Synchronize keys for users
  become: False
  authorized_key:
    user: core
    key: "{{ users[item].get('key') or lookup('file', 'files/keys/' + item + '.pub') }}"
    path: "{{ '/home/core/.ssh/authorized_keys.d/' + item }}"
    manage_dir: no
    exclusive: "{{ exclusive }}"
  with_items: "{{ user_groups[group] }}"
  notify:
    - update authorized_keys
