- name: List keys
  become: False
  shell: ls -1 /home/core/.ssh/authorized_keys.d/
  register: keys
  when: "{{ exclusive }}"
  changed_when: False

- name: Delete keys for user {{ item }}
  file: path=/home/core/.ssh/authorized_keys.d/{{ item }} state=absent
  when: exclusive and item not in user_groups[group]
  with_items: "{{ keys.stdout_lines }}"

- name: Add keys for user {{ item }}
  become: False
  authorized_key:
    user: core
    key: "{{ users[item].get('key') or lookup('file', 'files/keys/' + item + '.pub') }}"
    path: "{{ '/home/core/.ssh/authorized_keys.d/' + item }}"
    manage_dir: no
    exclusive: "{{ exclusive }}"
  with_items: "{{ user_groups[group] }}"

- name: Run update-ssh-keys
  become: False
  command: update-ssh-keys -l
  no_log: True
