- name: Add keys for user {{ item }}
  become: False
  authorized_key:
    user: core
    key: "{{ users[item].get('key') or lookup('file', 'files/keys/' + item + '.pub') }}"
    path: "{{ '/home/core/.ssh/authorized_keys.d/' + item }}"
    manage_dir: no
  with_items: user_groups[group]

- name: Run update-ssh-keys
  become: False
  command: update-ssh-keys -l
  no_log: True
